version: '3'
services:
    web:
        image: nginx:latest
        container_name: web
        ports:
            - '8000:80'
            - '9000:9000'
        volumes:
            - ./html:/var/www/html
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        build: .
        container_name: php-debug
        image: php:7-fpm
        volumes:
            - ./html:/var/www/html
            - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug-2.ini
        environment:
            XDEBUG_CONFIG: remote_host=10.1.10.17

